# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

User.destroy_all
Category.destroy_all
Quiz.destroy_all
Question.destroy_all
SubCategory.destroy_all

#User Instances
bree = User.create(name: "Bree", email: "bree@gmail.com", password: "3693" )

#Category and SubCategory Instances

#Cells
cells = Category.create(name: "Cells", img_url: 'back-end/images/cell.png', introduction: "Animals are Eukaryotes, which means their cells have a nucleus enclosed within a nuclear envelope. These cells are much larger than those of prokaryotes, having a volume of around 10,000 times greater than the prokaryotic cell.", conclusion: "test conclusion")
cell_subcategory_one = SubCategory.create(name: "Nucleus, Nucleolus, & Vacuole", description: "The nucleus is the most obvious organelle in any eukaryotic cell. It is enclosed in a double membrane and communicates with the surrounding cytosol via numerous nuclear pores. Within each nucleus is nuclear chromatin that contains the organism’s genome. The chromatin is efficiently packaged within the small nuclear space. Genes within the chromatin are made of deoxyribonucleic acid (DNA). The DNA stores the organism’s entire encoded genetic information. The DNA is similar in every cell of the body, but depending on the specific cell type, some genes may be turned on or off - that's why a liver cell is different from a muscle cell, and a muscle cell is different from a fat cell. When a cell is dividing, the nuclear chromatin (DNA and surrounding protein) condenses into chromosomes that are easily seen by microscopy. The prominent structure in the nucleus is the nucleolus. The nucleolus produces ribosomes, which move out of the nucleus and take positions on the rough endoplasmic reticulum where they are critical in protein synthesis. A vacuole is a membrane-bound sac that plays roles in intracellular digestion and the release of cellular waste products. In animal cells, vacuoles are generally small. Vacuoles tend to be large in plant cells and play several roles: storing nutrients and waste products, helping increase cell size during growth, and even acting much like lysosomes of animal cells. The plant cell vacuole also regulates turgor pressure in the cell. Water collects in cell vacuoles, pressing outward against the cell wall and producing rigidity in the plant. Without sufficient water, turgor pressure drops and the plant wilts.", category_id: cells.id)
cell_subcategory_two = SubCategory.create(name: "Mitochondria, Ribosomes, & Golgi Apparatus", description: "Mitochondria provide the energy a cell needs to move, divide, produce secretory products, contract - in short, they are the power centers of the cell. They are about the size of bacteria but may have different shapes depending on the cell type. Mitochondria are membrane-bound organelles, and like the nucleus have a double membrane. The outer membrane is fairly smooth. But the inner membrane is highly convoluted, forming folds (cristae) when viewed in cross-section. The cristae greatly increase the inner membrane's surface area. It is on these cristae that food (sugar) is combined with oxygen to produce ATP - the primary energy source for the cell. Ribosomes are packets of RNA and protein that play a crucial role in both prokaryotic and eukaryotic cells. They are the site of protein synthesis. Each ribosome comprises two parts, a large subunit and a small subunit. Messenger RNA from the cell nucleus is moved systematically along the ribosome where transfer RNA adds individual amino acid molecules to the lengthening protein chain. The Golgi apparatus is a membrane-bound structure with a single membrane. It is actually a stack of membrane-bound vesicles that are important in packaging macromolecules for transport elsewhere in the cell. The stack of larger vesicles is surrounded by numerous smaller vesicles containing those packaged macromolecules. The enzymatic or hormonal contents of lysosomes, peroxisomes and secretory vesicles are packaged in membrane-bound vesicles at the periphery of the Golgi apparatus.", category_id: cells.id)
cell_subcategory_three = SubCategory.create(name: "Lysosome, Smooth & Rough Endoplasmic Reticulum", description: "Lysosomes contain hydrolytic enzymes necessary for intracellular digestion. They are common in animal cells, but rare in plant cells. Hydrolytic enzymes of plant cells are more often found in the vacuole. Throughout the eukaryotic cell, especially those responsible for the production of hormones and other secretory products, is a vast network of membrane-bound vesicles and tubules called the endoplasmic reticulum, or ER for short. The ER is a continuation of the outer nuclear membrane and its varied functions suggest the complexity of the eukaryotic cell. The smooth endoplasmic reticulum is so named because it appears smooth by electron microscopy. Smooth ER plays different functions depending on the specific cell type including lipid and steroid hormone synthesis, breakdown of lipid-soluble toxins in liver cells, and control of calcium release in muscle cell contraction. Rough endoplasmic reticulum appears "pebbled" by electron microscopy due to the presence of numerous ribosomes on its surface. Proteins synthesized on these ribosomes collect in the endoplasmic reticulum for transport throughout the cell.", category_id: cells.id)

#Macromolecules
macromolecules = Category.create(name: "Macromolecules", img_url: 'back-end/images/macromolecules.png', introduction: "Food provides the body with the nutrients it needs to survive. Many of these critical nutrients are biological macromolecules necessary for life. These macromoleculess, polymers, are built from different combinations of smaller organic molecules, monomers. The three biological macromolecules we will discuss are proteins, carbohydrates, and lipids.", conclusion: "test conclusion")
macromolecules_subcategory_one = SubCategory.create(name: "Proteins", description: "Proteins are one of the most abundant organic molecules in living systems and have the most diverse range of functions of all macromolecules. Proteins may be structural, regulatory, contractile, or protective; they may serve in transport, storage, or membranes; or they may be toxins or enzymes. Each cell in a living system may contain thousands of proteins, each with a unique function. Their structures, like their functions, vary greatly.", category_id: macromolecules.id)
macromolecules_subcategory_two = SubCategory.create(name: "Carbohydrates", description: "Carbohydrates are, in fact, an essential part of our diet; grains, fruits, and vegetables are all natural sources of carbohydrates. Carbohydrates provide energy to the body, particularly through glucose, a simple sugar that is a component of starch and an ingredient in many staple foods. Carbohydrates also have other important functions in humans, animals, and plants.", category_id: macromolecules.id)
macromolecules_subcategory_three = SubCategory.create(name: "Lipids", description: "Lipids include a diverse group of compounds that are largely nonpolar in nature. This is because they are hydrocarbons that include mostly nonpolar carbon–carbon or carbon–hydrogen bonds. Non-polar molecules are hydrophobic (“water fearing”), or insoluble in water. Lipids perform many different functions in a cell. Cells store energy for long-term use in the form of fats. Lipids also provide insulation from the environment for plants and animals.", category_id: macromolecules.id)

#Metabolism
metabolism = Category.create(name: "Metabolism", img_url: 'back-end/images/metabolism.png', introduction: "All living things must have an unceasing supply of energy and matter. The transformation of this energy and matter within the body is called metabolism.", conclusion: "test conclusion")
metabolism_subcategory_one = SubCategory.create(name: "Catabolism and Anabolism", description: "Catabolism is destructive metabolism. Typically, in catabolism, larger organic molecules are broken down into smaller constituents. This usually occurs with the release of energy (usually as ATP). Anabolism is constructive metabolism. Typically, in anabolism, small precursor molecules are assembled into larger organic molecules. This always requires the input of energy (often as ATP).", category_id: metabolism.id)
metabolism_subcategory_two = SubCategory.create(name: "Autotrophic vs. Heterotrophic Nutrition", description: "Green plants, algae, and some bacteria are autotrophs, aka self-feeders. Most of them use the energy of sunlight to assemble inorganic precursors, chiefly carbon dioxide and water, into the array of organic macromolecules of which they are made. The process is photosynthesis. Photosynthesis makes the ATP needed for the anabolic reactions in the cell. All other organisms, including ourselves, are heterotrophs. We secure all our energy from organic molecules taken in from our surroundings ("food"). Although heterotrophs may feed partially (as most of us do) or exclusively on other heterotrophs, all the food molecules come ultimately from autotrophs. We may eat beef but the steer ate grass. Heterotrophs degrade some of the organic molecules they take in (catabolism) to make the ATP that they need to synthesize the others into the macromolecules of which they are made (anabolism).", category_id: metabolism.id)
metabolism_subcategory_three = SubCategory.create(name: "Heterotrophic Nutrition, continued", description: "Humans are heterotrophs. We are totally dependent on ingested preformed organic molecules to meet all our energy needs. We are also dependent on preformed organic molecules as the building blocks to meet our anabolic needs. The steps for converting food to energy in animals: Ingestion: taking food within the body (although as the figure shows, it is still topologically in the external world, not the internal). Digestion: The enzyme-catalyzed hydrolysis of polysaccharides (e.g., starch) to sugars, proteins to amino acids, fats to fatty acids and glycerol, and nucleic acids to nucleotides. Absorption into the body and transport to the cells. Absorption into cells." , category_id: metabolism.id)

#DNA Replication
dna_replication = Category.create(name: "DNA Replication", img_url: "back-end/images/dna.png", introduction: "DNA replication, also known as semi-conservative replication, is the process by which DNA is essentially doubled. It is an important process that takes place within the dividing cell.", conclusion: "test conclusion")
dna_subcategory_one = SubCategory.create(name: "Initiation", description: "DNA synthesis is initiated at particular points within the DNA strand known as ‘origins’, which are specific coding regions. These origins are targeted by initiator proteins, which go on to recruit more proteins that help aid the replication process, forming a replication complex around the DNA origin. There are multiple origin sites, and when replication of DNA begins, these sites are referred to as replication forks. Within the replication complex is the enzyme DNA Helicase, which unwinds the double helix and exposes each of the two strands, so that they can be used as a template for replication. It does this by hydrolysing the ATP used to form the bonds between the nucleobases, therefore breaking the bond holding the two strands together. DNA Primase is another enzyme that is important in DNA replication. It synthesises a small RNA primer, which acts as a ‘kick-starter’ for DNA Polymerase. DNA Polymerase is the enzyme that is ultimately responsible for the creation and expansion of the new strands of DNA.", category_id: dna_replication.id)
dna_subcategory_two = SubCategory.create(name: "Elongation", description: "Once the DNA Polymerase has attached to the original, unzipped two strands of DNA (i.e. the template strands), it is able to start synthesising the new DNA to match the templates. It is essential to note that DNA polymerase is only able to extend the primer by adding free nucleotides to the 3’ end. One of the templates is read in a 3’ to 5’ direction, which means that the new strand will be formed in a 5’ to 3’ direction. This newly formed strand is referred to as the Leading Strand. Along this strand, DNA Primase only needs to synthesise an RNA primer once, at the beginning, to initiate DNA Polymerase. This is because DNA Polymerase is able to extend the new DNA strand by reading the template 3′ to 5′, synthesising in a 5′ to 3′ direction as noted above. However, the other template strand (the lagging strand) is antiparallel, and is therefore read in a 5’ to 3’ direction. Continuous DNA synthesis, as in the leading strand, would need to be in the 3′ to 5′ direction, which is impossible as we cannot add bases to the 5′ end. Instead, as the helix unwinds, RNA primers are added to the newly exposed bases on the lagging strand and DNA synthesis occurs in fragments, but still in the 5′ to 3′ direction as before. These fragments are known as Okazaki fragments.", category_id: dna_replication.id)
dna_subcategory_three = SubCategory.create(name: "Termination", description: "The process of expanding the new DNA strands continues until there is either no more DNA template left to replicate (i.e. at the end of the chromosome), or two replication forks meet and subsequently terminate. The meeting of two replication forks is not regulated and happens randomly along the course of the chromosome. Once DNA synthesis has finished, it is important that the newly synthesised strands are bound and stabilized.  With regards to the lagging strand, two enzymes are needed to achieve this; RNAase H removes the RNA primer that is at the beginning of each Okazaki fragment, and DNA Ligase joins fragments together to create one complete strand.", category_id: dna_replication.id)

#Photosynthesis
photosynthesis = Category.create(name: "Photosynthesis", img_url: "back-end/images/photosynthesis.png", introduction: "Photosynthesis is a process used by plants and other organisms to convert light energy into chemical energy that can later be released to fuel the organisms' activities", conclusion: "test conclusion")
photosynthesis_subcategory_one = SubCategory.create(name: "Overview", description: "The chemical energy is stored in carbohydrate molecules, such as sugars, which are synthesized from carbon dioxide and water – hence the name photosynthesis, from the Greek phōs (φῶς), "light", and sunthesis (σύνθεσις), "putting together". In most cases, oxygen is also released as a waste product. Most plants, most algae, and cyanobacteria perform photosynthesis; such organisms are called photoautotrophs. Photosynthesis is largely responsible for producing and maintaining the oxygen content of the Earth's atmosphere, and supplies most of the energy necessary for life on Earth.", category_id: photosynthesis.id)
photosynthesis_subcategory_two = SubCategory.create(name: "Energy Transfer", description: "Although photosynthesis is performed differently by different species, the process always begins when energy from light is absorbed by proteins called reaction centres that contain green chlorophyll pigments. In plants, these proteins are held inside organelles called chloroplasts, which are most abundant in leaf cells, while in bacteria they are embedded in the plasma membrane. In these light-dependent reactions, some energy is used to strip electrons from suitable substances, such as water, producing oxygen gas. The hydrogen freed by the splitting of water is used in the creation of two further compounds that serve as short-term stores of energy, enabling its transfer to drive other reactions: these compounds are reduced nicotinamide adenine dinucleotide phosphate (NADPH) and adenosine triphosphate (ATP), the "energy currency" of cells.", category_id: photosynthesis.id)
photosynthesis_subcategory_three = SubCategory.create(name: "Calvin Cycle & History", description: "In plants, algae and cyanobacteria, long-term energy storage in the form of sugars is produced by a subsequent sequence of light-independent reactions called the Calvin cycle; some bacteria use different mechanisms, such as the reverse Krebs cycle, to achieve the same end. In the Calvin cycle, atmospheric carbon dioxide is incorporated into already existing organic carbon compounds, such as ribulose bisphosphate (RuBP). Using the ATP and NADPH produced by the light-dependent reactions, the resulting compounds are then reduced and removed to form further carbohydrates, such as glucose. The first photosynthetic organisms probably evolved early in the evolutionary history of life and most likely used reducing agents such as hydrogen or hydrogen sulfide, rather than water, as sources of electrons. Cyanobacteria appeared later; the excess oxygen they produced contributed directly to the oxygenation of the Earth, which rendered the evolution of complex life possible. Today, the average rate of energy capture by photosynthesis globally is approximately 130 terawatts, which is about eight times the current power consumption of human civilization. Photosynthetic organisms also convert around 100–115 billion tons (91-104 petagrams) of carbon into biomass per year.", category_id: photosynthesis.id)

#Stretch Goal: Quiz & Question Instances
# cell_quiz = Quiz.create(score: 10, user_id: bree.id, category_id: cells.id)
# cell_question_one = Question.create(description: "Which organelle is the powerhouse of energy?", correct_answer: "Mitochondria", wrong_answer_one: "Rough ER", wrong_answer_two: "Nucleus", wrong_answer_three: "Golgi Apparatus", category_id: cells.id, quiz_id: cell_quiz.id)


puts "Good to go!"